num1=int(input('Enter no. 1:'))
num2=int(input('Enter no. 2:'))
sum=num1+num2
sub=(num1-num2)
mul=(num1*num2)
div=(num2/num1)
fdiv=(num2//num1)
mod=(num2%num1)
print(f'Adiition of {num1} and {num2} is {sum}.')
print(f'Subtraction of {num1} and {num2} is {sub}.')
print(f'Multiplication of {num1} and {num2} is {mul}.')
print(f'Division of {num2} by {num1} is {div}.')
print(f'Floor division of {num2} by {num1} is {fdiv}.')
print(f'Remainder when {num2} is divided by {num1} is {mod}.')